spring:
  jpa:
    open-in-view: false
    hibernate:      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect 
  datasource:    url: jdbc:mysql://localhost:3306/econtreras?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: econtreras_user
    password: abcd.123