spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
  datasource:
#    url: jdbc:mysql://localhost:3306/econtreras
    url: jdbc:mysql://192.168.0.141:3306/econtreras
    username: econtreras_user
    password: abcd.123
  jackson:
    default-property-inclusion: NON_NULL
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      file-size-threshold: 2KB
      max-request-size: 215MB
file:
    upload-dir: /tmp/uploads
api:
  messages:
    already-exist: El departamento que intenta agregar ya existe!
    internal-server-error: Ocurrió un error inesperado
